name: CI

on: [ workflow_dispatch, push, pull_request ]

jobs:
  ci_stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Fetch head
        uses: actions/checkout@v4

      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: $test-cache-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Format check
        run: cargo fmt --check

      - name: Clippy check
        run: cargo clippy --features=sample -- -D warnings

      - name: Build and Test
        env:
          RUST_LOG: debug
        run: cargo test --features=sample --verbose

  ci_msrv:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v4

      - name: Install rust MSRV
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85
          components: clippy

      - name: Clippy check
        run: cargo clippy --features=sample -- -D warnings
